#include <memory>
#include <nlohmann/json.hpp>
#include "../../agentlib/tool_registry.h"
#include "../../agentlib/tool_validator.h"
#include "crashdump_list.h"

namespace tools
{

struct crashdump_list_raw_args {
	int limit{20};
};

NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE_WITH_DEFAULT(crashdump_list_raw_args, limit);

class crashdump_list_validator : public agentlib::tool_validator
{
      public:
	bool is_pure() const override
	{
		return true;
	} // Only reading data

	std::string get_name() const override
	{
		return "crashdump_list";
	}
	std::string get_description() const override
	{
		return "Returns a markdown table of recent crashdumps (crashes) generated by commands in the sandbox, up to a specified limit.";;
	}

	nlohmann::json get_parameters_schema() const override
	{
		return {
		    {"type", "object"},
		    {"properties",
		     {{"limit",
		       {{"type", "integer"},
			{"description",
			 "Optional limit on the maximum number of recent crash dumps to return. Defaults to 20."},
			{"default", 20}}}}}};
	}

      protected:
	bool validate_args_impl(const nlohmann::json &args_json, const agentlib::tool_context & /*ctx*/,
				std::string &out_error) const override
	{
		try {
			crashdump_list_raw_args raw = args_json.get<crashdump_list_raw_args>();
			if (raw.limit <= 0) {
				out_error = "Validation Error: limit must be greater than 0.";
				return false;
			}
			args_.limit = raw.limit;
			return true;
		} catch (const std::exception &e) {
			out_error = "Argument parsing error: " + std::string(e.what());
			return false;
		}
	}

	std::unique_ptr<agentlib::llm_tool> create_tool_impl(const nlohmann::json & /*args*/) const override
	{
		return std::make_unique<crashdump_list_tool>(args_);
	}

      private:
	mutable crashdump_list_args args_;
};

REGISTER_TOOL(crashdump_list_validator)

} // namespace tools