#include <memory>
#include <nlohmann/json.hpp>
#include "../../agentlib/tool_registry.h"
#include "../../agentlib/tool_validator.h"
#include "crashdump_list.h"

namespace tools
{

class crashdump_list_validator : public agentlib::tool_validator
{
      public:
	bool is_pure() const override
	{
		return true;
	} // Only reading data

	std::string get_name() const override
	{
		return "crashdump_list";
	}
	std::string get_description() const override
	{
		return "Returns a markdown table of recent crashdumps (crashes) generated by commands in the sandbox. The table includes "
		       "PID, Timestamp, Executable, and Signal.";
	}

	nlohmann::json get_parameters_schema() const override
	{
		return {{"type", "object"}, {"properties", nlohmann::json::object()}};
	}

      protected:
	bool validate_args_impl(const nlohmann::json & /*args_json*/, const agentlib::tool_context & /*ctx*/,
				std::string & /*out_error*/) const override
	{
		return true;
	}

	std::unique_ptr<agentlib::llm_tool> create_tool_impl(const nlohmann::json & /*args*/) const override
	{
		return std::make_unique<crashdump_list_tool>();
	}
};

REGISTER_TOOL(crashdump_list_validator)

} // namespace tools