#include "coredump_list.h"
#include "../../agentlib/tool_validator.h"
#include "../../agentlib/tool_registry.h"
#include <memory>
#include <nlohmann/json.hpp>

namespace tools {

class coredump_list_validator : public agentlib::tool_validator {
public:
    bool is_pure() const override { return true; } // Only reading data

    std::string get_name() const override { return "coredump_list"; }
    std::string get_description() const override { return "Returns a markdown table of recent coredumps (crashes) generated by commands in the sandbox. The table includes PID, Timestamp, Executable, and Signal."; }
    
    nlohmann::json get_parameters_schema() const override {
        return {
            {"type", "object"},
            {"properties", nlohmann::json::object()}
        };
    }

protected:
    bool validate_args_impl(const nlohmann::json& /*args_json*/, const agentlib::tool_context& /*ctx*/, std::string& /*out_error*/) const override {
        return true;
    }

    std::unique_ptr<agentlib::llm_tool> create_tool_impl(const nlohmann::json& /*args*/) const override {
        return std::make_unique<coredump_list_tool>();
    }
};

REGISTER_TOOL(coredump_list_validator)

}