[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "@@PROJECT_NAME_LOWER@@"
version = "0.1.0"
description = "@@PROJECT_NAME@@ python application"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "@@AUTHOR_NAME@@", email = "@@AUTHOR_EMAIL@@" }]

[project.scripts]
@@EXECUTABLE_NAME@@ = "src.__main__:main"
