#pragma once

#include <string>
#include <vector>
#include "fs_utils.h"

enum class home_access_t {
    hidden,
    read_only,
    read_write
};

class command_runner {
public:
    command_runner() { apply_default_profile(); }
    virtual ~command_runner() = default;

    // Configuration Setters
    void set_bypass_sandbox(bool bypass) { bypass_sandbox_ = bypass; }
    void set_network_access(bool access) { network_access_ = access; }
    void set_allow_display(bool allow) { allow_display_ = allow; }
    void set_home_access(home_access_t access) { home_access_ = access; }
    void set_project_dir(const std::string& dir) { project_dir_ = dir; }
    void set_project_hash(const std::string& hash) { project_hash_ = hash; }
    void add_extra_rw_path(const std::string& path) { extra_rw_paths_.push_back(path); }
    void add_extra_ro_path(const std::string& path) { extra_ro_paths_.push_back(path); }
    void set_bypass_crashdump_check(bool bypass) { bypass_crashdump_check_ = bypass; }
    void set_use_pty(bool use_pty) { use_pty_ = use_pty; }
    void set_enable_crash_catcher(bool enable) { enable_crash_catcher_ = enable; }

    // Pre-defined Security Profiles
    void apply_default_profile();
    void apply_internal_profile();
    void apply_build_profile();
    void apply_strict_agent_profile();


    // The core execution engine.
    // - Handles popen/pclose internally.
    // - Uses poll() to ensure we don't block indefinitely without checking `should_continue()`.
    // - Parses the output stream into discrete lines (handling \r\n and partial buffers).
    // - Blocks until the process finishes or `should_continue()` returns false.
    // Returns the exit code (or a distinct error code if interrupted).
    int execute(const std::string& command);

    /**
     * @brief Formatted execution method.
     * SECURE-BY-DESIGN: Placeholder arguments `{}` are automatically shell-escaped
     * via fs_utils::escape_arg / fs_utils::escape_shell_arg to prevent command injection.
     */
    template <typename... Args>
    int execute(std::string_view fmt, const Args&... args) {
        return execute(fs_utils::format_command(fmt, args...));
    }

    // Retrieves and clears the most recent crashdump report generated by this runner.
    std::string get_new_crashdumps() {
        std::string res = last_crashdumps_report_;
        last_crashdumps_report_.clear();
        return res;
    }

    // Hook to rewrite the command before it is passed to popen.
    // This injects the sandboxing strategy (e.g., systemd-run) if not bypassed.
    virtual std::string build_command(const std::string& raw_command) const;

    /**
     * @brief Formatted build_command method.
     * SECURE-BY-DESIGN: Placeholder arguments `{}` are automatically shell-escaped
     * via fs_utils::escape_arg / fs_utils::escape_shell_arg to prevent command injection.
     */
    template <typename... Args>
    std::string build_command(std::string_view fmt, const Args&... args) const {
        return build_command(fs_utils::format_command(fmt, args...));
    }

protected:
    // ------------------------------------------------------------------------
    // Required Virtuals
    // ------------------------------------------------------------------------
    
    // Called sequentially for every raw chunk of output (stdout + stderr combined).
    // This allows subclasses to process progress bars (\r) or partial lines live.
    virtual void on_output_chunk(const std::string& chunk) = 0;

    // Legacy method for line-by-line parsing. Base class handles splitting chunks into lines.
    // If a subclass overrides on_output_chunk, this is never called automatically.
    // By default, the base implementation of on_output_chunk accumulates lines and calls this.
    virtual void on_output_line(const std::string& line) { (void)line; }

    // ------------------------------------------------------------------------
    // Optional Virtuals
    // ------------------------------------------------------------------------

    // Allows subclasses to interrupt a running command. 
    // The execution loop will poll this periodically. Default is always true.
    virtual bool should_continue() const {
        return true; 
    }


private:
    bool bypass_sandbox_{false};
    bool network_access_{false};
    bool allow_display_{false};
    home_access_t home_access_{home_access_t::hidden};
    std::string project_dir_;
    std::string project_hash_;
    std::vector<std::string> extra_rw_paths_;
    std::vector<std::string> extra_ro_paths_;
    bool bypass_crashdump_check_{false};
    bool use_pty_{false};
    bool enable_crash_catcher_{false};
    std::string last_crashdumps_report_;
};

class sync_command_runner : public command_runner {
public:
    // Convenience wrapper that executes and returns the accumulated string directly
    std::string execute_and_get_output(const std::string& command);

    /**
     * @brief Formatted execution wrapper.
     * SECURE-BY-DESIGN: Placeholder arguments `{}` are automatically shell-escaped
     * via fs_utils::escape_arg / fs_utils::escape_shell_arg to prevent command injection.
     */
    template <typename... Args>
    std::string execute_and_get_output(std::string_view fmt, const Args&... args) {
        return execute_and_get_output(fs_utils::format_command(fmt, args...));
    }
    
    int get_exit_code() const { return exit_code_; }

protected:
    void on_output_chunk(const std::string& chunk) override;
    void on_output_line(const std::string& line) override;

private:
    std::string full_output_;
    std::string line_buffer_;
    int exit_code_ = 0;
};
