// THIS FILE IS AUTOGENERATED BY scripts/embed_system_docs.py FROM FILES IN system/
// DO NOT EDIT THIS FILE DIRECTLY! EDIT THE ORIGIN FILES IN system/ INSTEAD.

#pragma once
#include <unordered_map>
#include <string>
#include <string_view>

namespace turbostar {

inline const std::unordered_map<std::string, std::string_view> &get_embedded_system_docs()
{
    static const std::unordered_map<std::string, std::string_view> docs = {
        {"workflows/bugfixing.md", R"raw_embed(# Bugfixing Protocol (Assess – Reproduce – Verify – Fix – Confirm)

When fixing a reported bug (wrong output, missed feature, edge-case logic, or test
failure), you **MUST** execute the following protocol in order. It guarantees the fix
is correct, covered, and confined to the true root cause.

---

## Step 1: ASSESS (Gauge test coverage in the suspected area)

Before writing or changing any source, determine how well the affected area is tested
so you know how much guard-railing the fix will need.

- **Locate the relevant test file(s)** and check the coverage around the suspected
  surface (matching format/flag/type combinations, boundaries, edge cases).
- **If testing is weak or absent, add more (or many) baseline tests first** to pin the
  current behavior — under-tested areas are where regressions ship — before attempting
  to reproduce or fix. Note that this may uncover other bugs in the underlying code.
- **Record what is already covered** so you add tests for the gaps rather than
  duplicating existing ones.

---

## Step 2: REPRODUCE (Get a failing case BEFORE touching source)

Do not edit source until you can observe the bug.

- **Build a minimal failing reproducer** from the report (minimal inputs, minimal
  format/arguments/call site).
- **Prefer the project's real test harness** (`fs_run_tests` on the existing suite)
  over throwaway probes. The correct reproducer *is* a new test in the trailing
  baseline suite from Step 1.
- **Confirm the failure** is observed (test FAILS, or output differs from expected)
  before proceeding. An unobserved bug is not yet a bug you understand.
- **Admit defeat** when the issue is so complicated that no reasonable test can be
  created — raise this early rather than burning time on speculative fixes.

---

## Step 3: VERIFY (Pin the expected behavior with a failing test)

With baseline coverage in place (Step 1), add the test that pins the *correct*,
post-fix behavior **before** implementing the fix.

- **Add a test for the reported case** that asserts the correct (post-fix) behavior.
- **Cover the fix's neighbors**, not just the exact report — flag combinations,
  boundaries, wide/narrow variants.
- **Run the new test and confirm it FAILS** against the current code. A test that
  passes before the fix is testing nothing.

---

## Step 4: FIX (Root cause, not symptom)

Locate and fix the true root cause.

- **Trace to the origin** of the incorrect behavior, not the first place you notice it
  (see `crash_analysis.md` for the What/How/Where technique applied to failure states).
- **Root-Cause Fix (Preferred)**: change the origin site so the behavior is correct.
- **No Superficial Symptom Patches**: avoid masking, special-casing, or
  swallow-guarding at the symptoms unless that is valid domain logic.
- **Add comments**: Presume something is unusual in this area; add comments that
  describe the correct high level intent and boundary conditions.
---

## Step 5: CONFIRM (Fail-then-Pass)

- **Re-run the full relevant suite**: the new tests must now PASS, and existing
  tests must not REGRESS (run neighboring test files too).
- **Sanity-check neighbors**: confirm the fix did not alter unrelated behaviors
  (e.g. default and adjacent flag paths).
- Keep the change **focused**: code + tests for this bug only. Leave chore/tracking
  files, unrelated formatting, and changelog curation out unless instructed otherwise.

---

*Companion protocol: `crash_analysis.md` for crash/undefined-state analysis. Share the
test-verification (fail-then-pass) and root-cause-over-symptom principles with it to
avoid drift.*)raw_embed"},
        {"workflows/code_review.md", R"raw_embed(# Code Review Subagent Workflow

## Guidelines
- **File Slicing**: Do not review more than 10 files or 1,500 lines of code in a single subagent call. Group larger file lists logically and invoke `perform_code_review` separately for each group.
- **Checklists & Instructions**: Provide overall context in `instructions` and supply a checklist of specific review items in the `todos` vector.
- **Post-Review**: Call `list_code_review_items` to get a concise summary table of active findings, and `get_code_review_item` to retrieve details.
- **Resolution**: Use `resolve_code_review_item` when issues are addressed or ruled out.
)raw_embed"},
        {"workflows/crash_analysis.md", R"raw_embed(# Crash & Bug Analysis Protocol (What – How – Where)

When analyzing a crash report, log failure, core dump, or test failure, you **MUST** execute the 3-step **What – How – Where** analysis protocol below.

---

## Step 1: WHAT (Crash / Failure Identification)
Identify the precise failure condition and location from the failure report and source code.
- **Objective**: Determine the exact line, symbol, and invalid state that triggered the failure (e.g., `[editor_events.cpp:142] Pointer 'doc' was nullptr during dereference`).
- **Output**: Formulate a concise 1–2 sentence "What" summary.

---

## Step 2: HOW (Root-Cause Tracing)
Trace backwards through execution paths to determine *why* the invalid state occurred. Repeat the "How" query recursively (up to 3–4 levels) until reaching the true root cause.

Classify the analysis under one of these categories:
- **A. Positive How (Explicit Assignment)**: An explicit execution path assigned an invalid value (e.g., `nullptr`, invalid index, out-of-bounds size). Trace the assignment chain step-by-step with Q&A queries.
- **B. Negative How (Missing Initialization / Unhandled Path)**: The state was never initialized or assigned a valid value. Determine why normal initialization/assignment code path was bypassed.
- **C. Unknowable How (Insufficient Data)**: Do **NOT** write a speculative fix. Improve observability by adding structured logging, assertions, or telemetry at key decision points so future runs capture complete state.
- **D. Testcase Verification**: Create a minimal testcase that reproduces the root-cause state. Verify that the testcase **FAILS** prior to applying the fix and **PASSES** once the fix is applied.

---

## Step 3: WHERE (Fix Location)
Determine the correct location in the codebase for the fix based on Step 2.
1. **Root-Cause Fix (Preferred)**: Place the fix at the origin site identified in Step 2.
2. **No Superficial Symptom Patches**: Avoid placing a simple NULL check or swallow-exception block at the crash site unless handling the condition locally is valid domain logic.
)raw_embed"},
        {"languages/c17.md", R"raw_embed(# C17 Development Guidelines

## Code Conventions
- **Language Standard**: ISO C17 (`-std=c17`).
- **Include Guards**: Prefer `#pragma once` or standard `#ifndef` include guards for header files.
- **Const Correctness**: Use `const` for read-only pointer arguments (`const char *`, `const uint8_t *`).
- **Memory Management**: Check return values of `malloc`, `calloc`, and `realloc`. Ensure every allocated resource is freed and pointers cleared (`ptr = NULL`). Note that `free(NULL)` is valid, so avoid unnecessary `if (ptr) free(ptr)` wrappers.
- **Initialization**: Always initialize variables and struct instances (e.g. `{0}` or `memset`) prior to use.
- **File Organization**: Place each module/component in a dedicated `.c` file and matching `.h` header in the same directory.

## Security Considerations
- **Security-First Mindset**: Adopt a security-first mindset across all generated code.
- **Untrusted Input**: Clearly label variables and parameters holding untrusted (user/network) data in comments.
- **Early Validation**: Sanity-check and validate all untrusted input as early as possible.
- **Bounds Checking**: Verify all buffer and array accesses against underflows and overflows.
- **Buffer Size Parameters**: Always pass explicit buffer size parameters (`size_t buf_size`) alongside pointer arguments. Avoid unsafe string functions (`strcpy`, `sprintf`); use bounded alternatives (`snprintf`, `strncpy`).

## Code Commenting Conventions
- **Intent over Logic**: Focus comments on rationale (the "why") and design goals rather than restating code logic.
- **Ownership & Constraints**: Document pointer ownership, memory lifecycles, thread-safety expectations, and function constraints.
- **Mutex Declarations**: Precede every mutex declaration in header files with a comment block explaining:
  1. What specific data or resources the mutex protects.
  2. Locking rules, lifecycle, or ordering guidelines.
)raw_embed"},
        {"languages/cpp23.md", R"raw_embed(# C++23 Development Guidelines

## Code Conventions
- **Language Standard**: C++23. Use modern features (`std::format`, `std::string_view`, `std::span`, `constexpr`, `noexcept`, structured bindings, ranged for loops).
- **Include Guards**: Prefer `#pragma once`.
- **Memory Management**: Follow RAII strictly; avoid raw `new` and `delete`, favoring `std::make_unique` and `std::make_shared`.
- **String & Sequence Handling**: Prefer `std::string_view` for read-only string function parameters over `const std::string &`, and `std::span<const T>` for read-only contiguous sequence parameters over `const std::vector<T> &` to avoid unnecessary heap allocations; use `std::string` / `std::vector` when ownership or mutation is required. Avoid raw `char *` except when interfacing with C APIs or the OS kernel.
- **Standard Library**: Prefer C++ Standard Library containers and algorithms over custom implementations.
- **File Organization**: Place each class in a dedicated `.cpp` file and matching header in the same directory.
- **Constexpr & Qualifiers**: Label methods and parameters `constexpr`, `const`, `std::string_view`, `std::span`, and `noexcept` when appropriate.

## Security Considerations
- **Security-First Mindset**: Adopt a security-first mindset across all generated code.
- **Untrusted Input**: Clearly label variables and parameters holding untrusted (user/network) data in comments.
- **Early Validation**: Sanity-check and validate all untrusted input as early as possible.
- **Bounds Checking**: Verify all buffer and array accesses against underflows and overflows.

## Code Commenting Conventions
- **Intent over Logic**: Focus comments on rationale (the "why") and design goals rather than restating code logic.
- **Ownership & Constraints**: Document ownership, thread-safety expectations, and function constraints.
- **Mutex Declarations**: Precede every mutex declaration in header files with a comment block explaining:
  1. What specific data or resources the mutex protects.
  2. Locking rules, lifecycle, or ordering guidelines.
- **Subclass Header Documentation**: When creating a base class or adding a subclass, include or update a comment block table directly above the parent class definition detailing all derived subclasses and their file locations:
```cpp
/*

# subclasses of <parent class>

| subclass     | filename                                             |
| ------------ | ---------------------------------------------------- | 
| <subclass 1> | <project relative path to the header for subclass 1> |

*/
```)raw_embed"},
        {"languages/cpp23_short.md", R"raw_embed(# C++23 Development Guidelines Summary
- **Standard & Memory**: C++23. Strictly follow RAII (`make_unique`/`make_shared`, avoid raw `new`/`delete`). Use modern features (`std::format`, `std::string_view`, `std::span`, `constexpr`, `noexcept`, `#pragma once`, ranged for loops).
- **Security-First**: Adopt a security-first mindset across all generated code. Document and sanity-check untrusted input early and verify buffer/array bounds.
- **Organization**: Place each class in matching `.h`/`.cpp` files.
- **Comments**: Document rationale ("why"), thread ownership, and mutex locking rules.
- *Full guidelines & templates available at `system://languages/cpp23.md`.*)raw_embed"},
        {"languages/default.md", R"raw_embed(# General Development Guidelines

## Security Considerations
- **Security-First Mindset**: Adopt a security-first mindset across all generated code.
- **Untrusted Input**: Clearly label variables and parameters holding untrusted (user/network) data in comments.
- **Early Validation**: Sanity-check and validate all untrusted input as early as possible.
- **Bounds Checking**: Verify all buffer and array accesses against underflows and overflows.

## Code Commenting Conventions
- **Intent over Logic**: Focus comments on rationale (the "why") and design goals rather than restating code implementation logic.
- **Ownership & Constraints**: Document ownership, memory lifecycles, thread-safety expectations, and function constraints.
- **Synchronization Declarations**: Precede every mutex or lock declaration in header files with a comment block explaining:
  1. What specific data or resources the mutex protects.
  2. Locking rules, lifecycle, or ordering guidelines.
)raw_embed"},
        {"languages/default_short.md", R"raw_embed(# General Development Guidelines Summary
- **Security-First**: Adopt a security-first mindset across all generated code. Sanity-check untrusted input early and verify buffer/array bounds.
- **Comments**: Focus comments on rationale ("why"), thread ownership, memory lifecycles, and mutex locking rules rather than restating code logic.
- *Full guidelines available at `system://languages/default.md`.*
)raw_embed"},
        {"languages/python311.md", R"raw_embed(# Python 3.11 Development Guidelines

## Code Conventions
- **Language Standard**: Python 3.11+.
- **Style Guide**: Follow PEP8 style guide and naming conventions.
- **Type Annotations**: Consistently add PEP 484 type annotations (`type_a | type_b`, `list[str]`, `dict[str, int]`) to all function arguments, return values, and variable declarations.
- **Virtual Environments**: Prefer running Python scripts within isolated environments or VFS `tmp://` scratch spaces.

## Security Considerations
- **Security Validation**: Code executed or created must pass `bandit` security checks (no `shell=True` in subprocess calls, no unvalidated `eval()` or `exec()`).
- **Input Sanitization**: Validate all external paths, user input strings, and API payloads before processing.
)raw_embed"},
        {"languages/rust2021.md", R"raw_embed(# Rust 2021 Development Guidelines

## Code Conventions
- **Language Edition**: Rust 2021 Edition.
- **Ownership & Borrowing**: Follow Rust ownership, borrowing, and lifetime rules strictly. Prefer immutable borrows (`&T`) and RAII (`Drop`).
- **Error Handling**: Use `Result<T, E>` and `Option<T>` with `?` operator propagation. Avoid `panic!` or `unwrap()` in library code.
- **Safety**: Avoid `unsafe` blocks unless interfacing directly with C FFI or OS primitives. Document all safety invariants with `# Safety` comments.
- **Documentation**: Document all public types, traits, and functions with doc comments (`///`).
)raw_embed"},
        {"languages/systemverilog.md", R"raw_embed(# SystemVerilog Guidelines (IEEE 1800)

## Core Principles
- **Modeling Precision**: Use `logic` for general design signals rather than legacy `reg` or `wire`. Reserve `wire` strictly for structural nets with multiple drivers (e.g., tri-state buses).
- **Explicit Procedural Blocks**:
  - `always_comb` for pure combinational logic (enforces sensitivity list inference and zero-delay simulation semantics).
  - `always_ff @(posedge clk or negedge rst_n)` for sequential registers and flip-flops.
  - `always_latch` when level-sensitive latches are deliberately intended.
- **Non-Blocking vs. Blocking Assignments**:
  - Use non-blocking assignments (`<=`) inside `always_ff` blocks.
  - Use blocking assignments (`=`) inside `always_comb` blocks.
  - Never mix blocking and non-blocking assignments to the same signal.
- **Interfaces & Modports**: Bundle inter-module signals into `interface` definitions with dedicated `modport` views for master/slave roles.
- **Packages**: Encapsulate shared parameters, types, `typedef struct packed`, and enumeration definitions inside named `package` declarations and import them explicitly (`import my_pkg::*;`).
- **SystemVerilog Assertions (SVA)**:
  - Embed immediate (`assert (cond) else $error(...)`) and concurrent (`assert property (...)`) checks directly in RTL.
- **Synthesis & Linting**:
  - Keep RTL synthesizable; avoid delays (`#`), unsynthesizable initial blocks, and non-constant division.
  - Check code using `verilator --lint-only -Wall` or similar linter.
)raw_embed"},
        {"languages/typescript.md", R"raw_embed(# TypeScript / JavaScript Guidelines

## Core Principles
- **Strict Typing**: Enable `strict: true` in `tsconfig.json`. Avoid `any`; use `unknown` or specific interface types.
- **Async Programming**: Prefer `async` / `await` over explicit Promise chains.
- **Modules**: Use ES module syntax (`import` / `export`).
)raw_embed"},
        {"languages/verilog.md", R"raw_embed(# Verilog / SystemVerilog Guidelines

## Core Principles
- **Modeling**: Separate combinational (`always_comb` / `always @(*)`) logic from sequential (`always_ff` / `always @(posedge clk)`) logic.
- **Assignments**: Use non-blocking assignments (`<=`) in sequential blocks and blocking assignments (`=`) in combinational blocks.
- **Synthesis**: Avoid un-synthesizable constructs (delays `#`, initial blocks for logic) in RTL modules.
)raw_embed"},
    };
    return docs;
}

} // namespace turbostar
