name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y meson ninja-build libncursesw5-dev python3 libcpp-httplib-dev nlohmann-json3-dev libre2-dev libsqlite3-dev libdtl-dev libunwind-dev gcc-14 g++-14
      - name: Build
        run: CXX=g++-14 meson setup build && ninja -C build
      - name: Test
        run: meson test -C build